version: '3.2'

services:
  arthas-tunnel-web:
    image: wf2311/arthas-tunnel-web:latest
    container_name: arthas-tunnel
    ports:
      - "7777:7777"
      - "9999:9999"
      - "6666:6666"
    environment:
      - JVM_OPTS=-Xmx256m -Xms256m -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=6666
      - SERVER_PORT=9999
      - TUNNEL_SERVER_PORT=7777
      - NACOS_ADDR=192.168.40.56:8848
      - NACOS_NAMESPACE=dev